Repository BENTO-o/backend, pull requests merged in 2024-11, with the labels that each got.

#6 User login and register API
  backend/build.gradle
  backend/src/main/java/bento/backend/config/SecurityConfig.java
  backend/src/main/java/bento/backend/constant/ErrorMessages.java
  backend/src/main/java/bento/backend/controller/UserController.java
  backend/src/main/java/bento/backend/domain/User.java
  backend/src/main/java/bento/backend/dto/request/UserLoginRequest.java
  backend/src/main/java/bento/backend/dto/request/UserRegistrationRequest.java
  backend/src/main/java/bento/backend/exception/ConflictException.java
  backend/src/main/java/bento/backend/exception/NotFoundException.java
  backend/src/main/java/bento/backend/exception/UnauthorizedException.java
  backend/src/main/java/bento/backend/repository/UserRepository.java
  backend/src/main/java/bento/backend/security/JwtTokenProvider.java
  backend/src/main/java/bento/backend/service/UserService.java
  backend/src/main/java/bento/backend/service/auth/AuthService.java
  backend/src/main/java/bento/backend/service/user/PasswordService.java
  backend/src/main/java/bento/backend/service/user/UserService.java
  backend/src/main/resources/application.yml
  docker-compose.yaml
Labels: enhancement, help wanted

#7 User social login
  backend/build.gradle
  backend/src/main/java/bento/backend/config/AppConfig.java
  backend/src/main/java/bento/backend/config/SecurityConfig.java
  backend/src/main/java/bento/backend/constant/ErrorMessages.java
  backend/src/main/java/bento/backend/controller/OAuthController.java
  backend/src/main/java/bento/backend/controller/UserController.java
  backend/src/main/java/bento/backend/domain/Role.java
  backend/src/main/java/bento/backend/domain/User.java
  backend/src/main/java/bento/backend/dto/response/OAuthLoginResponse.java
  backend/src/main/java/bento/backend/exception/ResourceNotFoundException.java
  backend/src/main/java/bento/backend/exception/ValidationException.java
  backend/src/main/java/bento/backend/security/CustomOAuth2User.java
  backend/src/main/java/bento/backend/security/JwtTokenProvider.java
  backend/src/main/java/bento/backend/service/auth/AuthService.java
  backend/src/main/java/bento/backend/service/auth/CustomOAuth2UserService.java
  backend/src/main/java/bento/backend/service/user/UserService.java
  backend/src/main/resources/application.yml
  docker-compose.yaml
Labels: enhancement

#9 Revert "Issue template"
  .github/ISSUE_TEMPLATE/bug_template.yml
  .github/ISSUE_TEMPLATE/feature_template.yml
Labels: documentation, enhancement

#10 Revert "Revert "Issue template""
  .github/ISSUE_TEMPLATE/bug_template.yml
  .github/ISSUE_TEMPLATE/feature_template.yml
Labels: bug
